### ISSUE TITLE
Upgrade etcd-viewer to work with etcd v3

### ISSUE THREAD

**Issue by raoofm** [nikfoundas/etcd-viewer#8]
It has been 3 months since the relase of etcd v3. Any plans of supporting it?

**Comment by qihanglys** [comment]
I also use etcd v3 version, will support for the v3 version?

**Comment by nikfoundas** [comment]
@raoofm  @qihanglys Thanks for your comments and interest guys! I will try as soon as possible to include support for etcd v3. The issue is that this project is a mainly a hobby and unfortunately I don't have much free time these days.

**Comment by halcyon22** [comment]
It seems to work with my v3 cluster, but maybe I'm missing something.

**Comment by kamphaus** [comment]
@halcyon22 etcd v3 has two different persistence backends:
* one v2 backend
* one v3 backend

Both can contain different data and are independent of each other.
Depending on which API version you use to connect to the cluster you access a different backend.
A consequence of this is that when you want to change the API version of your clients, you need to migrate your data somehow (https://coreos.com/etcd/docs/latest/op-guide/v2-migration.html).

So what you noticed is probably that you connected to the v2 backend.
